
ASSUME CS:CODE, DS:DATA
DATA SEGMENT
LIST DB 0ABH,0DFH,0FFH,01EH,05CH,0D1H
COUNT EQU 5D
SMALLEST DW 01H DUP(?)

DATA ENDS
CODE SEGMENT
START:  MOV AX, DATA
        MOV DS,AX
        MOV SI, OFFSET LIST
        MOV CL, COUNT
        MOV AL,[SI]
AGAIN:  CMP AL,[SI+1]
        JC NEXT
        MOV AL,[SI+1]
NEXT:   INC SI
        DEC CL
        JNZ AGAIN
        MOV SI, OFFSET SMALLEST
        MOV [SI],AL
        HLT
CODE ENDS
END START

ret